### ISSUE TITLE
share methods and variables 

### ISSUE THREAD

**Issue by francescoagati** [rubikscraft/tcl-js#3]
how,
there is a mode for share methods and variables between tcl and js?

**Comment by rubikscraft** [comment]
No sorry, at the moment this is not yet possible

**Comment by rubikscraft** [comment]
You can now add your own JS functions to the interpreter with the `addSimpleProcedure` and `addAdvancedProcedure` functions on a `Tcl` instance. [Documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/rubikscraft/tcl-js/master/docs/classes/_tcl_.tcl.html#addadvancedprocedure)

**Comment by francescoagati** [comment]
wow thanks :-)
i will try it
